<?php declare(strict_types=1);

namespace Zonos\ZonosSdk\Connectors\Auth;

use Saloon\Http\Connector;

/**
 * Main connector class for interacting with the Auth API
 *
 * Handles authentication, base configuration, and provides access to
 * Auth-related queries and mutations through trait implementations.
 */
class AuthConnector extends Connector
{
  use AuthQueries;
  use AuthMutations;

  /**
   * Create a new Auth connector instance
   *
   * @param string $credentialToken Authentication token for API access
   * @param string $baseUrl Base URL for API endpoints
   */
  public function __construct(
    protected string $credentialToken,
    protected string $baseUrl,
  ) {
  }

  /**
   * Resolve the base URL for API endpoints
   *
   * @return string The complete base URL for the API
   */
  public function resolveBaseUrl(): string
  {
    return $this->baseUrl;
  }

  /**
   * Get the default headers for API requests
   *
   * @return array<string, string> Array of default headers
   */
  protected function defaultHeaders(): array
  {
    return [
      'Accept' => 'application/json',
      'Content-Type' => 'application/json',
      'credentialToken' => $this->credentialToken,
      'senderCredential' => 'credential_live_c2b26e14-3099-463e-ac11-6881049425a2'// TODO: We need to replace this with the one being generated by Braden
    ];
  }
}